# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0004_auto_20180619_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='ATTRIBUTE9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
