# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('busqueda', '0006_auto_20180619_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=5)),
                ('TITULO', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ConfUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.Bodega')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
