# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0007_bodega_confusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='NOMBRE',
            new_name='Nombre',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='TITULO',
        ),
        migrations.AddField(
            model_name='bodega',
            name='Localizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
