# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0009_pec'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='Provincia',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='Telefono',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
