# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0012_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(max_length=20)),
                ('Bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.Bodega')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.PEC')),
            ],
        ),
    ]
