# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0014_auto_20180622_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pec',
            name='CHECK_D',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pec',
            name='CHECK_LD',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
