# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0015_auto_20180622_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='PRIMARY_UOM_CODE',
            field=models.CharField(max_length=100),
        ),
    ]
