# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0016_auto_20180626_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegas',
            name='PRIMARY_UOM_CODE',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pec',
            name='PRIMARY_UOM_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
