# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0017_auto_20180626_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='Nombre',
            field=models.CharField(max_length=6),
        ),
    ]
