# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0020_subgrupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='Titulo',
            field=models.CharField(max_length=100),
        ),
    ]
