# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0021_auto_20180705_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.Clases')),
            ],
        ),
        migrations.AlterField(
            model_name='subgrupos',
            name='Subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.Grupos'),
        ),
        migrations.AlterField(
            model_name='subgrupos',
            name='Titulo',
            field=models.CharField(max_length=100),
        ),
    ]
