# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0024_auto_20180705_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupos',
            new_name='Grupo',
        ),
    ]
