# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0025_auto_20180705_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grupo', models.CharField(max_length=2)),
                ('Titulo', models.CharField(max_length=100)),
                ('Clase', models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='busqueda.Clases')),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='Grupo',
        ),
        migrations.RemoveField(
            model_name='subgrupos',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='subgrupos',
            name='Grupo',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='busqueda.Clases'),
        ),
        migrations.AlterField(
            model_name='subgrupos',
            name='Subgrupo',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
