# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0026_auto_20180705_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgrupos',
            name='Grupo',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='busqueda.Grupos'),
        ),
    ]
