# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0033_auto_20180706_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupos',
            new_name='Grupo',
        ),
    ]
