# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0034_auto_20180706_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grupo', models.CharField(max_length=2)),
                ('Titulo', models.CharField(max_length=100)),
                ('Clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.Clases')),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='Clase',
        ),
        migrations.AlterField(
            model_name='subgrupo',
            name='Grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.Grupos'),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
