# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0035_auto_20180706_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='Clase',
        ),
        migrations.RemoveField(
            model_name='subgrupo',
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Grupos',
        ),
        migrations.DeleteModel(
            name='SubGrupo',
        ),
    ]
