# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0038_auto_20180706_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgrupo',
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='SGrupo',
        ),
    ]
