# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0041_auto_20180711_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgrupo',
            name='Cod',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pec',
            name='CLASE',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
