# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0042_auto_20180718_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='pec',
            name='DIGITOSFINALES',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pec',
            name='CODIGO',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
