# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0043_auto_20180718_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFinales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clases', models.CharField(max_length=2)),
                ('Digitos', models.CharField(max_length=2)),
                ('Fraccion', models.CharField(max_length=100)),
                ('Entero', models.CharField(max_length=100)),
            ],
        ),
    ]
