# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0044_dfinales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfinales',
            name='Digitos',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dfinales',
            name='Entero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='dfinales',
            name='Fraccion',
            field=models.CharField(max_length=5),
        ),
    ]
