# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0045_auto_20180718_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfinales',
            name='Entero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dfinales',
            name='Fraccion',
            field=models.CharField(max_length=10),
        ),
    ]
