# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
