# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0003_auto_20180611_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORGANIZATION_CODE', models.CharField(max_length=5)),
                ('SEGMENT1', models.CharField(max_length=15)),
                ('ANTERIOR', models.CharField(max_length=15)),
                ('DESCRIPTION', models.TextField(max_length=200)),
                ('ATTRIBUTE3', models.CharField(blank=True, max_length=200, null=True)),
                ('ATTRIBUTE4', models.CharField(blank=True, max_length=200, null=True)),
                ('CANTIDAD', models.CharField(blank=True, max_length=10, null=True)),
                ('PRIMARY_UOM_CODE', models.CharField(max_length=5)),
                ('LOCALIZADOR', models.CharField(max_length=8)),
            ],
        ),
    ]
